### ISSUE TITLE
Blank screen  when pressing the button to activate the plug in 

### ISSUE THREAD

**Issue by Tewodros34** [trashhalo/logseq-graph-analysis#15]
![Uploading Screen Shot 2022-07-06 at 9.07.13 PM.png…]()

**Comment by trashhalo** [comment]
@Tewodros34 that would happen if an error occurred when you open the plugin. can you click this button in menu an you will see some red text in console. paste the red text in here! it will help me fix it
<img width="410" alt="Screen Shot 2022-07-06 at 12 11 07 PM" src="https://user-images.githubusercontent.com/177491/177595931-0a7e631f-77f0-4718-9072-14e95adaaad1.png">

**Comment by Tewodros34** [comment]
Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/sethyuan/logseq-plugin-ol/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
index.d0b19e62.js:171 #ol loaded
raw.githubusercontent.com/sethyuan/logseq-plugin-tocgen/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()
index.9abd1a65.js:3834 #tocgen loaded
raw.githubusercontent.com/sethyuan/logseq-plugin-wrap/master/src/translations/en-US.json:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by ruudschouten** [comment]
I have the same issue, but my console did display an error;

![image](https://github.com/trashhalo/logseq-graph-analysis/assets/1363911/39e25c01-bba9-44ee-ab4b-f7aba61d131b)

I am using version 0.10.2 of the plugin, with Logseq version 0.9.6.
I hope this is of any help to resolve this issue 🙂

**Comment by mrparalon** [comment]
There were a problem with a blank aliases, and it is fixed now by  #51 . Could anyone check it?

**Comment by nol683** [comment]
Hello. I am having a similar issue with the plugin. Every time I click on it, it remains blank despite the navigation bar being present (but not able to search for anything and anytime I try to search, the plugin closes). It was working well previously and when I tested it on a new loqseq graph it works but when I returned to my current logseq graph it returns to being blank. I wonder if there is something about my current graph (the only thing I can think of that I did out of the norm in my workflow is using the Undo function (ctrl+z) to re-arrange some pages I had made. Though its a vague assumption since the plugin stopped working around that time for me)  

![Screenshot (283)](https://github.com/trashhalo/logseq-graph-analysis/assets/147878125/6ee93c6c-51d3-4207-bfc1-2b7f2511923c). 
On the screenshot this primarily shows: 
Uncaught (in promise) TypeError: Cannot read 
properties of undefined (reading 'id')
    at Jf (index.c7b1360c.js:12:143967)
    at index.c7b1360c.js:12:145099
    at Array.map (<anonymous>)
    at Bt (index.c7b1360c.js:12:145060)
    
I am using Logseq version 0.9.10 and version 0.10.6 of the plugin. Still new to this environment and will appreciate any assistance.

**Comment by ruudschouten** [comment]
> There were a problem with a blank aliases, and it is fixed now by #51 . Could anyone check it?

I just updated the plugin to 0.10.6 and it works now, so it did fix it for me :)

**Comment by mrparalon** [comment]
@nol683 Could you try to re-index your graph? 

If it doesn't help, you could try to install an unpacked version of the plugin and run it using `yarn dev`? It will give much better debug info to spot an issue.

**Comment by nol683** [comment]
Thank you, have re-indexed my graph and it's now working. Thank you again!
