### ISSUE TITLE
add a filter mode for search

### ISSUE THREAD

**Issue by trashhalo** [trashhalo/logseq-graph-analysis#18]
nmartin84 — Today at 12:39 PM
I'm loving the CoCitation algorithm.. Question though, is it possible to add a filter option to the graph? Keyword based, and it limits the visible nodes that match the keyword entered?

Stephen Solka — Today at 1:28 PM
To clarify, are you saying that like you put into a search box, the word cow and only notes that have the word cow in their name would be visible? Would their connections be visible as well? It might help if you say what's the use case like maybe you have too many notes and it's hard to read or something

nmartin84 — Today at 1:40 PM
Correct, only nodes that match the keyword, and their connections.

Stephen Solka — Today at 1:42 PM
I can do that. Do you want connections of connections etc too? A->B->C , A B and C would be visible if you search A

nmartin84 — Today at 1:42 PM
That would be great, and yeah connections of connections, or maybe even an option to choose "how many hops away?" so the user can tweak as they like?

**Comment by mruderman** [comment]
> "...yeah connections of connections, or maybe even an option to choose "how many hops away?" so the user can tweak as they like?

I'd like to second the connections of connections request. In obsidian it is the "Depth" slider option for local graphs...a toggle for ingoing and outgoing links would also be incredible. Thank you @trashhalo for developing this!

**Comment by trashhalo** [comment]
0.5.0 has filter!
