### ISSUE TITLE
Adjusting any setting resets the graph view

### ISSUE THREAD

**Issue by bezark** [trashhalo/logseq-graph-analysis#20]
It seems that as of the latest version, clicking on any of the settings or nodes resets the zoom of the graph back to default. This makes navigating since the user looses their focus any time a setting is adjusted. I believe in previous versions this was not the case.

Thank you so much for this plugin though. It's really interesting and I'm very excited to see how it continues to develop!

**Comment by trashhalo** [comment]
Wow! That'd be super annoying. Thanks for letting me know. I have a fix out shortly

**Comment by bezark** [comment]
Thank you very much!

**Comment by trashhalo** [comment]
fixed in 0.5.2!
