### ISSUE TITLE
Bug: Filtering with n hops can lead to an irreversible blank graph

### ISSUE THREAD

**Issue by Frikster** [trashhalo/logseq-graph-analysis#38]
When I filter my graph it works at first. But if I bring the n hops slider down, reversing it doesn't do anything.

**Steps to replicate**

- Search for a node with filter ticked
- Bring the n hops down: should work and you slowly only see so many hops from your search term.
- Try to increase n hops again: Nodes do not appear again and the only thing displayed is your one node

Only way out of this is to exit the plugin and reopen it.

**Comment by Frikster** [comment]
In fact, after step 3 the graph becomes completely unresponsive. No slider interaction does anything - whole graph just stays blank except for a single node.

**Comment by justaprussian** [comment]
I am also facing a blank graph after using filter-function - but in my case there seems to be no way to reset or restore. Neither exiting the plugin nor de- and reinstallation brings back the graph. This is odd, because I use two other graphs in my Logseq, which still work flawlessly.

**Comment by justaprussian** [comment]
After updating Logseq to Linux X_64 0.9.5 AppImage and Graph Analysis to 0.10.1 I've been trying to deal with this issue, facing more odds: 
There are three graphs A, B and C in my Logseq. 
B is the one with the corrupt Graph Analysis Graph. 
A and C work without problems. 
Switching from A to B and starting the plugin, brings up two different behaviours: 
Either the plugin remains blank with high load on processor or - and this is really odd - Graph A is shown. 
There is no way to bring up graph B in the plugin.

**Comment by Frikster** [comment]
That's disturbing. @trashhalo any chance we can get eyes on this? Is there perhaps a workaround?

**Comment by justaprussian** [comment]
Any idea or hint on howto make the plugin work for my affected graph again? Reindexing didn't help. It would be a really huge loss to me if it couldn't be brought back up again.

**Comment by Frikster** [comment]
@trashhalo @mrparalon I can confirm this issue is fixed and the graph filter works so beautifully now I am squealing with delight.

@justaprussian I fully uninstalled and reinstalled the plugin and all was well immediately. This probably wasn't needed and I probably could have just clicked the "check update" button, but it worked for me. To uninstall Logseq Graph Analysis go to your installed plugins, click the cog in the lower left and click uninstall. Then just reinstall and the plugin should work like a dream.
