### ISSUE TITLE
Include journals page?

### ISSUE THREAD

**Issue by ajk68** [trashhalo/logseq-graph-analysis#4]
Thanks for the amazing plugin! I use it a lot and love it! The graph analysis plugin was the only reason i was still using obsidian.

Not an issue, but a feature request. My graph has the vast amount of blocks in the Journals. I have commented out the lines where you exclude the journals pages in stores.ts, which makes the graph far more useful for me. It is a bit slower on first load, but still very usable once loaded. 

I've tried to add a checkbox to include journals pages, but failed. Would be great if this was an option, so i can use the marketplace version of the plugin.

**Comment by trashhalo** [comment]
Ya of course! I'll add a setting today!

**Comment by ajk68** [comment]
tnx! looking forward to it!

**Comment by trashhalo** [comment]
@ajk68 @hodanil version 0.2.0 now on markplace with a new plugin setting called journal. Its default off so you'd want to turn on in settings. Enjoy! If you think of other features please let me know. Looking for more ideas
<img width="945" alt="Screen Shot 2022-06-30 at 9 15 42 PM" src="https://user-images.githubusercontent.com/177491/176803498-8119cb81-5886-4cb1-a9f7-24acff76c7fd.png">
