### ISSUE TITLE
graph not loading

### ISSUE THREAD

**Issue by hdansou** [trashhalo/logseq-graph-analysis#48]
Hi! I am having issues loading the graph. The following error is seen in the console:

```
3index.6754c062.js:10 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).map is not a function
    at Ta (index.6754c062.js:10:129879)
    at Jt (index.6754c062.js:10:129076)
```

![image](https://github.com/trashhalo/logseq-graph-analysis/assets/536716/1909a28e-1eb2-45c9-986c-0d769b2683e0)

Any recommendations about this issue?

**Comment by mrparalon** [comment]
Could you try to run query 

```
#+BEGIN_QUERY
{:query [:find (pull ?b (*)) :in $ :where (?b :block/refs)]}
#+END_QUERY
```

You can past this in any page in logseq.

Also it will useful if you could try to install unpacked plugin which is run in a dev mode

**Comment by hdansou** [comment]
@mrparalon, thanks for the reply.

The provided query runs and returns 4500 results.
Last weekend, I tried the unpacked versions 0.10.2 and 0.10.1 and I had the same result.

Should I try an older one?

**Comment by mrparalon** [comment]
If you run unpacked plugin using `yarn dev` - it should give more readable output in console. Could you pls check it?

**Comment by hdansou** [comment]
I was able to narrow down the issue. When we have a property `alias:: ` with an empty value on a namespace page, it causes the error:

![image](https://github.com/trashhalo/logseq-graph-analysis/assets/536716/57df40ee-70c1-4f82-a6a6-b1319dc68ed9)

**Comment by mrparalon** [comment]
I think it will require just adding empty string or null check there?
@hdansou do you want to try to implement it?
