### ISSUE TITLE
Graph analysis button don't show up in toolbar after updated to v0.10.4

### ISSUE THREAD

**Issue by MaxGeneris** [trashhalo/logseq-graph-analysis#57]
Hi! 
I updated last night to latest version and now the button to display the graph is not showing up any more.
Please see below the error. I'm running LogSeq on mac os.

![Screenshot 2023-10-29 at 16 07 49](https://github.com/trashhalo/logseq-graph-analysis/assets/133965749/78cfb494-ba61-4798-8040-04c04a76f52e)

Below you can see where the error is getting thrown.

![Screenshot 2023-10-29 at 16 13 08](https://github.com/trashhalo/logseq-graph-analysis/assets/133965749/0a41879d-7aad-46e9-ad9c-126589d34e0b)

Please let me know if is there anything else I can do to help.

Thanks, 
Max

**Comment by mrparalon** [comment]
Thanks for report. Fixed in latest version!
