### ISSUE TITLE
Display Issues in logseq 0.10

### ISSUE THREAD

**Issue by Plexprofile** [trashhalo/logseq-graph-analysis#66]
<img width="1280" alt="image_4" src="https://github.com/trashhalo/logseq-graph-analysis/assets/139643082/8f62b70e-04af-4b3f-9e7e-546c7cffdce1">
The viewer settings panel was covered in darkness

**Comment by mrparalon** [comment]
I can't reproduce it. 

What theme do you use? Could you pls toggle dark mode back and forth?

**Comment by mrparalon** [comment]
Can't reproduce, closing it
