### ISSUE TITLE
Filters not persistent across logseq restarts

### ISSUE THREAD

**Issue by hhornburg** [trashhalo/logseq-graph-analysis#72]
Hi,

I noticed that the filters are all removed when logseq is restarted. Would it be possible to make them persistent? It would save me from re-copying the queries and colors everytime I reopen logseq.

Thanks!

I'm using Logseq 0.10.5 with Graph Analysis 0.11.0

**Comment by mrparalon** [comment]
Looks like some bugs, filters should be written to plugin settings
