### ISSUE TITLE
A non-existent link between pages appears

### ISSUE THREAD

**Issue by Vova3141592** [trashhalo/logseq-graph-analysis#79]
A non-existent link between two unlinked pages appears in the graph if there is a third page that has links to both pages in the same block. If these links are in different blocks, no non-existent link appears.

This is what it looks like in Logseq's graph view:

![изображение](https://github.com/trashhalo/logseq-graph-analysis/assets/134244133/8a7d766a-e817-4fb9-a71f-15d948b1e41b)

This is how the bug looks in the Logseq Graph Analysis:

![изображение](https://github.com/trashhalo/logseq-graph-analysis/assets/134244133/16f91318-3f4f-4ed2-a77d-4e2c3a16db64)

The bug occurs when two links are in the same block in a linking page:

![изображение](https://github.com/trashhalo/logseq-graph-analysis/assets/134244133/f38fe69e-93fe-4dd9-8f94-68b0a14aad94)

If you place two links in different blocks in the linking page, the bug goes away:

![изображение](https://github.com/trashhalo/logseq-graph-analysis/assets/134244133/d77a5e13-d5b6-445f-b0a4-4cd44958f24e)
![изображение](https://github.com/trashhalo/logseq-graph-analysis/assets/134244133/9722ae57-75d6-4158-9a29-5988dfbdbefc)

In my opinion, this is a serious bug, because the whole point of the plugin is lost because of this bug: how to analyze the graph if a bunch of non-existent links are shown?

Logseq version — 0.10.9
Logseq Graph Analysis version — 0.11.3

**Comment by Vova3141592** [comment]
In my opinion, this is a serious bug, because the whole point of the plugin is lost because of this bug: how to analyze the graph if a bunch of non-existent links are shown?

**Comment by mrparalon** [comment]
@Vova3141592 I have feeling that it is by design. If you mention 2 thing in 1 block, that means that they are connected and graph plugin tries to show it
@trashhalo Am I correct?

**Comment by trashhalo** [comment]
> @Vova3141592 I have feeling that it is by design. If you mention 2 thing in 1 block, that means that they are connected and graph plugin tries to show it
> @trashhalo Am I correct?

That's exactly right. I was trying to find and graph connections within the same block. The text describes a relationship between pages. Not all of my note.content was written in outliner style with lots of nesting.

Funny enough I made a Public YouTube video on everything I learned about logseq connections when making this plugin. https://youtu.be/yJOox5FbuAM?si=R5tCIk82S9EXT0qn

**Comment by naught101** [comment]
Any chance there could be an option to disable this inclusion? I would love a version of the graph that only includes explicit links between pages.

**Comment by naught101** [comment]
Oh, it seems like direct links from a page to another page are not included at all (unless I'm seeing a bug)? Perhaps would it be possible to ADD that as an option too? So you can have either just within-block links, just block-to-page links, or both displayed?
